CREATE
    EXTENSION postgis;
CREATE
    EXTENSION postgis_topology;
CREATE
    EXTENSION fuzzystrmatch;
CREATE
    EXTENSION postgis_tiger_geocoder;


CREATE TABLE posts
(
    id                   bigint generated by default as identity NOT NULL,
    created_at           timestamp(6) DEFAULT now()              NOT NULL,
    updated_at           timestamp(6)                            NULL,
    title                varchar                                 NULL,
    user_id              bigint                                  NULL,
    store_id             bigint                                  NULL,
    services_ids         _int8                                   NULL,
    deleted_at           timestamp(6)                            NULL,
    adv_navigate_type    varchar                                 NULL,
    adv_link             varchar                                 NULL,
    adv_keyword          varchar                                 NULL,
    enable_sub_title_adv boolean      DEFAULT false              NULL,
    adv_index            int                                     NULL,
    adv_search_sort      varchar                                 NULL,
    adv_label_btn        varchar                                 NULL,
    is_active            boolean      DEFAULT true               NULL,
    adv_target_id        bigint                                  NULL,
    priority             int          DEFAULT 1                  NULL,
    min_price_sort       int                                     NULL,
    max_price_sort       int                                     NULL,
    CONSTRAINT "posts_pk" PRIMARY KEY (id)
);

CREATE TABLE post_reports
(
    id                   bigint generated by default as identity NOT NULL,
    created_at           timestamp(6) DEFAULT now()              NOT NULL,
    updated_at           timestamp(6)                            NULL,
    post_id              bigint                                  NULL,
    user_id              bigint                                  NULL,
    reason               varchar                                 NULL,
    post_reports_content varchar                                 NULL,
    post_reports_type    varchar                                 NULL,
    comment_id           bigint                                  NULL,
    CONSTRAINT "post_reports_pk" PRIMARY KEY (id),
    CONSTRAINT "post_reports_posts_pk" FOREIGN KEY (post_id) REFERENCES posts (id)
);

CREATE TABLE post_views
(
    id             bigint generated by default as identity NOT NULL,
    post_id        bigint                                  NULL,
    user_id        bigint                                  NULL,
    user_seller_id bigint                                  NULL,
    created_at     timestamp(6) DEFAULT now()              NOT NULL,
    updated_at     timestamp(6)                            NULL,
    CONSTRAINT "post_views_pk" PRIMARY KEY (id),
    CONSTRAINT "post_views_posts_pk" FOREIGN KEY (post_id) REFERENCES posts (id)
);

CREATE TABLE post_likes
(
    id         bigint generated by default as identity NOT NULL,
    created_at timestamp(6) DEFAULT now()              NOT NULL,
    updated_at timestamp(6)                            NULL,
    post_id    bigint                                  NULL,
    user_id    bigint                                  NULL,
    CONSTRAINT "post_likes_pk" PRIMARY KEY (id),
    CONSTRAINT "post_likes_posts_pk" FOREIGN KEY (post_id) REFERENCES posts (id)
);

CREATE TABLE post_comments
(
    id         bigint generated by default as identity NOT NULL,
    created_at timestamp(6) DEFAULT now()              NOT NULL,
    updated_at timestamp(6)                            NULL,
    post_id    bigint                                  NULL,
    user_id    bigint                                  NULL,
    "content"  varchar                                 NULL,
    medias_ids _int8                                   NULL,
    parent_id  bigint                                  NULL,
    user_ids   _int8                                   NULL,
    CONSTRAINT "post_comments_pk" PRIMARY KEY (id),
    CONSTRAINT "post_comments_posts_pk" FOREIGN KEY (post_id) REFERENCES posts (id)
);

CREATE TABLE post_blocks
(
    id         bigint generated by default as identity NOT NULL,
    post_id    bigint                                  NULL,
    user_id    bigint                                  NULL,
    reason     varchar                                 NULL,
    created_at timestamp(6) DEFAULT now()              NOT NULL,
    updated_at timestamp(6)                            NULL,
    CONSTRAINT "post_blocks_pk" PRIMARY KEY (id),
    CONSTRAINT "post_blocks_posts_pk" FOREIGN KEY (post_id) REFERENCES posts (id)
);


CREATE TABLE post_medias
(
    id               bigint generated by default as identity NOT NULL,
    post_id          bigint                                  NULL,
    media_id         bigint                                  NULL,
    is_featured      boolean      DEFAULT false              NOT NULL,
    created_at       timestamp(6) DEFAULT now()              NOT NULL,
    updated_at       timestamp(6)                            NULL,
    post_medias_type varchar                                 NULL,
    CONSTRAINT "post_medias_pk" PRIMARY KEY (id)
);

CREATE TABLE plans
(
    id                     bigint generated by default as identity NOT NULL,
    plans_type             varchar                                 NULL,
    plans_name             varchar                                 NULL,
    price_vi               numeric(10, 2) DEFAULT 0                NULL,
    price_en               numeric(10, 2) DEFAULT 0                NULL,
    duration               int                                     NULL,
    unit                   varchar                                 NULL,
    standard_listing       boolean                                 NULL,
    allow_kar              boolean        DEFAULT false            NULL,
    price_kar              int                                     NULL,
    manual_renew           boolean                                 NULL,
    auto_renew             boolean                                 NULL,
    show_on_latest_listing boolean                                 NULL,
    show_on_main_listing   boolean                                 NULL,
    is_active              boolean        DEFAULT true             NULL,
    created_at             timestamp      DEFAULT now()            NOT NULL,
    updated_at             timestamp                               NULL,
    CONSTRAINT "plans_pk" PRIMARY KEY (id)
);

CREATE TABLE post_status_logs
(
    id                     bigint generated by default as identity NOT NULL,
    created_at             timestamp(6) DEFAULT now()              NOT NULL,
    updated_at             timestamp(6)                            NULL,
    post_id                bigint                                  NULL,
    updated_by_id          bigint                                  NULL,
    plan_id                bigint                                  NULL,
    remaining_plan_day     numeric                                 NULL,
    remaining_plan_minutes numeric                                 NULL,
    remaining_plan_unit    varchar                                 NULL,
    post_status_logs_type  varchar                                 NULL,
    note                   varchar                                 NULL,
    CONSTRAINT "post_status_logs_pk" PRIMARY KEY (id),
    CONSTRAINT "post_status_logs_posts_pk" FOREIGN KEY (post_id) REFERENCES posts (id),
    CONSTRAINT "post_status_logs_plans_pk" FOREIGN KEY (plan_id) REFERENCES plans (id)
);


create table attachment
(
    id                  bigint generated by default as identity
        constraint attachment_pk
            primary key,
    mime_type           varchar,
    file_name           varchar,
    thumbnail           varchar,
    file_path_sm        varchar,
    file_path_lg        varchar,
    file_path_original  varchar,
    checksum            varchar,
    size                varchar,
    description         varchar,
    created_by          bigint,
    created_at          timestamp  default now()                  not null,
    updated_by          bigint,
    updated_at          timestamp,
    status              varchar(2) default 'A'::character varying not null,
    version             integer    default 1,
    folder              varchar    default 'uploads'::character(1),
    source              varchar    default 's3'::character(1),
    is_sync_vultr       boolean    default false,
    is_sync_vultr_error boolean    default false
);

create table attachment_map
(
    id                 bigint generated by default as identity
        constraint attachment_map_pk
            primary key,
    code               varchar,
    display_name       varchar,
    object_type        varchar,
    object_id          bigint,
    client_upload_code varchar,
    description        varchar,
    created_by         bigint,
    created_at         timestamp  default now()                  not null,
    updated_by         bigint,
    updated_at         timestamp,
    status             varchar(2) default 'A'::character varying not null,
    order_no           integer,
    attachment_id      bigint
        constraint attachment_map_attachment_id_fk
            references attachment (id)
);

CREATE TABLE center_driver_license_attachment
(
    id            bigint generated by default as identity NOT NULL,
    center_id     bigint                                  NOT NULL,
    attachment_id bigint                                  NOT NULL,
    created_at    timestamp                               NOT NULL DEFAULT now(),
    updated_at    timestamp                               NULL,
    CONSTRAINT center_driver_license_medias_pk PRIMARY KEY (id),
    CONSTRAINT center_driver_license_attachment_attachments_id_fk FOREIGN KEY (attachment_id) REFERENCES attachment (id)
);

create table hashtags
(
    id         bigint generated by default as identity
        constraint hashtags_pk
            primary key,
    hashtag    varchar,
    created_at timestamp(6) not null default now()
);

create table hashtags_map
(
    id            bigint generated by default as identity
        constraint hashtags_map_pk
            primary key,
    object_id     bigint       not null,
    object_type   varchar      not null,
    hashtags_type varchar,
    created_at    timestamp(6) not null default now(),
    hashtag_id    bigint       not null
        constraint hashtags_map_hashtags_fk references hashtags (id)
);
create table services
(
    id            bigint generated by default as identity
        constraint services_pk
            primary key,
    created_at    timestamp(6) default now() not null,
    updated_at    timestamp(6),
    title         varchar,
    price         numeric      default 0,
    user_id       bigint                     not null,
    store_id      bigint                     not null,
    duration_time varchar,
    description   varchar,
    sort          numeric      default 0,
    deleted_at    timestamp(6)
);





