CREATE EXTENSION postgis;
CREATE EXTENSION postgis_topology;
CREATE EXTENSION fuzzystrmatch;
CREATE EXTENSION postgis_tiger_geocoder;

create table user_auth
(
    id               bigint generated by default as identity not null,
    user_name        varchar                                 not null,
    user_info_id     bigint                                  null,
    user_info_no     varchar                                 null,
    user_pwd_hash    varchar                                 null,
    user_salt        varchar                                 null,
    device_id        varchar                                 null,
    number_of_device int                                     null,
    platform_version varchar                                 null,
    created_at       timestamp default current_timestamp,
    updated_at       timestamp,
    status           varchar                                 null,
    constraint user_auth_uq_i unique (user_name),
    constraint user_auth_pk primary key (id)
);


create table devices
(
    id                   bigint generated by default as identity not null,
    device_name          varchar                                 null,
    status               varchar                                 null,
    mobile_serial_number varchar                                 null,
    mobile_mac_address   varchar                                 null,
    mobile_imei          varchar                                 null,
    mobile_root_status   varchar                                 null,
    created_at           timestamp default current_timestamp,
    updated_at           timestamp,
    constraint devices_pk primary key (id)
);


create table device_auth
(
    id                  bigint generated by default as identity not null,
    device_id           bigint                                  not null,
    user_auth_id        bigint                                  not null,
    user_name           varchar                                 null,
    public_key          text                                    null,
    status              varchar(1)                              null,
    secret_key          varchar                                 null,
    service_public_key  text                                    null,
    service_private_key text                                    null,
    created_at          timestamp default current_timestamp,
    updated_at          timestamp,
    constraint device_auth_pk primary key (id),
    constraint fk_device_auth_device_id foreign key (device_id) references devices (id),
    constraint fk_device_auth_user_auth_id foreign key (user_auth_id) references user_auth (id)
);

create table user_device
(
    id                 bigint generated by default as identity not null,
    user_auth_id       bigint                                  not null,
    device_id          bigint                                  not null,
    number_of_device   int                                     null,
    priority           int                                     null,
    primary_device     varchar(1)                              null,
    last_accessed_time timestamp(6)                            null,
    status             varchar(1)                              null,
    token              varchar(100)                            null,
    old_token          varchar(100)                            null,
    check_old_token    varchar(100)                            null,
    token_change_date  date                                    null,
    biology_method     varchar(2)                              null,
    token_status       smallint                                null,
    token_user_pwd     varchar(255)                            null,
    created_at         timestamp default current_timestamp,
    updated_at         timestamp,
    constraint user_device_pk primary key (id),
    constraint fk_user_device_user_auth_id foreign key (user_auth_id) references user_auth (id),
    constraint fk_user_device_device_id foreign key (device_id) references devices (id)
);

create table role
(
    role_id     bigint generated by default as identity not null,
    description varchar(255)                            null,
    name        varchar(255)                            null,
    status      varchar(255)                            null,
    created_at  timestamp default current_timestamp,
    updated_at  timestamp,
    constraint role_pk primary key (role_id)
);



create table permission
(
    name        varchar(255) not null,
    description varchar(255) null,
    constraint permission_pk primary key (name)
);

create table user_roles
(
    user_auth_id bigint not null,
    role_id      bigint not null,
    primary key (user_auth_id, role_id),
    constraint fk_user_roles_user_auth_id
        foreign key (user_auth_id) references user_auth (id),
    constraint fk_user_roles_role_id
        foreign key (role_id) references role (role_id)
);

create table role_permissions
(
    role_id          bigint       not null,
    permissions_name varchar(255) not null,
    primary key (role_id, permissions_name),
    constraint fk_role_permissions_permissions_name
        foreign key (permissions_name) references permission (name),
    constraint fk_role_permissions_role_id
        foreign key (role_id) references role (role_id)
);


create table area
(
    id          integer     not null
        constraint area_pk
            primary key,
    area_type   varchar(5)  not null,
    area_code   varchar(15) not null
        constraint area_code_unique
            unique,
    parent_code varchar(15),
    province    varchar(10),
    district    varchar(10),
    precinct    varchar(10),
    area_name   varchar(200),
    full_name   varchar(500),
    order_no    integer,
    status      varchar(2)  not null,
    map_code    varchar(15),
    created_at  timestamp default CURRENT_TIMESTAMP,
    updated_at  timestamp
);


create table user_info
(
    id                                   bigint                                    not null,
    user_auth_id                         bigint                                    not null,
    area_id                              int                                       null,
    user_no                              varchar(45)                               null,
    full_name                            varchar(255)                              null,
    first_name                           varchar(255)                              null,
    middle_name                          varchar(255)                              null,
    last_name                            varchar(255)                              null,
    display_name                         varchar(255)                              null,
    birthday                             date                                      null,
    email                                varchar(255)                              null,
    phone                                varchar(255)                              null,
    avatar                               varchar(1000)                             null,
    gender                               varchar(45)                               null,
    address_detail                       varchar(255)                              null,
    full_address                         varchar(300)                              null,
    description                          varchar(1000)                             null,
    created_at                           timestamp default current_timestamp,
    updated_at                           timestamp                                 null,
    status                               varchar(45)                               null,
    enable_notification                  boolean   default true                    not null,
    enable_email_notification            boolean   default false                   not null,
    enable_sms                           boolean   default false                   not null,
    enable_promotions_notification       boolean   default true                    not null,
    enable_promotions_email_notification boolean   default true                    not null,
    language                             varchar   default 'vi'::character varying not null,
    latitude                             double precision,
    longitude                            double precision,
    location                             geography(Point, 4326),
    constraint members_pk primary key (id),
    constraint fk_user_auth_id foreign key (user_auth_id) references user_auth (id),
    constraint fk_user_area_id foreign key (area_id) references area (id)
);


















