spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: authentication_service
              uri: http://localhost:8080
              predicates:
                - Path=/authentication/**
            - id: post_service
              uri: http://localhost:8081
              predicates:
                - Path=/post/**
            - id: customer_service
              uri: http://localhost:8082
              predicates:
                - Path=/customer/**

server:
  port: 8888

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} | %-5level | %X{traceId:-N/A} | %thread | %C{1}.%M:%L | %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} | %-5level | %X{traceId:-N/A} | %thread | %C{1}.%M:%L | %msg%n"
  file:
    name: logs/api_gateway.log


