spring:
  application:
    name: customer-service
  profiles:
    active: local

server:
  port: 8082
  servlet:
    context-path: /customer

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} | %-5level | %X{traceId:-N/A} | %thread | %C{1}.%M:%L | %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} | %-5level | %X{traceId:-N/A} | %thread | %C{1}.%M:%L | %msg%n"
  file:
    name: logs/customer_service.log
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html


